name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run script on push or pull_request to main
      run: |
        # Ejecutar el script 
        ./primer\ parcial
